version: '3.4'

services:
  ms.cassandra.db:
    image: cassandra

  ms.sql.employees.db:
    image: mcr.microsoft.com/mssql/server:latest   

  ms.mongo.attendance.db:
    image: mongo

  ms.users.api:
    image: ${DOCKER_REGISTRY-}msusers
    build:
      context: .
      dockerfile: ms.users/ms.users.api/Dockerfile

  ms.employees.api:
    image: ${DOCKER_REGISTRY-}msemployees
    build:
      context: .
      dockerfile: ms.employees/ms.employees.api/Dockerfile

  ms.attendances.api:
    image: ${DOCKER_REGISTRY-}msattendances
    build:
      context: .
      dockerfile: ms.attendances/ms.attendances.api/Dockerfile

  ms.rabbitmq.bus:
    image: rabbitmq:3-management

  elasticsearch:
    container_name: elasticsearch
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    ports:
      - "9200:9200"
    volumes:
      - C://Docker/MicroServices/ElasticSearch:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node

  kibana:
    container_name: kibana
    restart: always
    image: docker.elastic.co/kibana/kibana:7.15.1
    ports:
      - "5601:5601" 
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200