version: '3.4'

services:
  ms.cassandra.db:
    container_name: ms.cassandra.db
    restart: always
    volumes:
      - C://Docker/MicroServices/Cassandra:/var/lib/cassandra
    ports:
      - "9042:9042"

  ms.users.api:
    container_name: ms.users.api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__Hostname=ms.cassandra.db
      - Communication__EventBus__HostName=ms.rabbitmq.bus 
    ports:
      - "9000:80"
    depends_on:
      - ms.cassandra.db
      - ms.rabbitmq.bus

  ms.sql.employees.db:
    container_name: ms.sql.employees.db
    restart: always
    volumes:
      - C://Docker/MicroServices/SQLServer:/var/opt/mssql/data
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ".123Pass456."
      ACCEPT_EULA: "Y"

  ms.employees.api:
    container_name: ms.employees.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__EmployeeDB__Hostname=ms.sql.employees.db
      - ConnectionStrings__EmployeeDB__Catalogue=EmployeesAttendance
      - ConnectionStrings__EmployeeDB__User=sa
      - ConnectionStrings__EmployeeDB__Password=.123Pass456.
      - Communication__EventBus__HostName=ms.rabbitmq.bus
      - Communication__External__AttendanceApiUrl=http://ms.attendances.api:80
    ports:
      - "9010:80"
    depends_on:
      - ms.sql.employees.db
      - ms.rabbitmq.bus
      - ms.attendances.api

  ms.mongo.attendance.db:
    container_name: ms.mongo.attendance.db
    hostname: mongo
    restart: always
    volumes:
      - C://Docker/MicroServices/Mongo:/data/db
    ports:
      - "27017:27017"

  ms.attendances.api:
    container_name: ms.attendances.api
    environment:
      - APSNETCORE_ENVIORAMENT=Development
      - ConnectionStrings__Attendance__Hostname=mongo
      - ConnectionStrings__Attendance__DataBase=DbHistoricalAttendance
      - ConnectionStrings__Attendance__Collection=Attendances
      - ConnectionStrings__Attendance__Port=27017
      - Communication__EventBus__HostName=ms.rabbitmq.bus 
    ports:
      - "9020:80"
    depends_on:
      - ms.mongo.attendance.db
      - ms.rabbitmq.bus

  ms.rabbitmq.bus:
    container_name: ms.rabbitmq.bus
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"